import { jsPDF } from "jspdf"

interface TicketData {
  ticketNumber: string
  qrCode?: string | null
  attendeeName?: string | null
  attendeeEmail?: string | null
  ticketType: {
    name: string
    price?: number
    currency?: string
  }
  event: {
    title: string
    startDate: string
    startTime?: string | null
    endDate?: string | null
    endTime?: string | null
    venueName?: string | null
    address?: string | null
    city?: string | null
    country?: string
    eventFormat?: string
    organizer?: {
      organizerName?: string | null
    }
  }
}

export function generateTicketPdf(ticket: TicketData) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a5" })
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header bar
  doc.setFillColor(88, 80, 236) // primary purple
  doc.rect(0, 0, pageWidth, 28, "F")

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont("helvetica", "bold")
  doc.text("EventsKona", pageWidth / 2, 12, { align: "center" })
  doc.setFontSize(10)
  doc.setFont("helvetica", "normal")
  doc.text("E-Ticket", pageWidth / 2, 20, { align: "center" })

  let y = 38

  // Event title
  doc.setTextColor(30, 30, 30)
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  const titleLines = doc.splitTextToSize(ticket.event.title, pageWidth - 30)
  doc.text(titleLines, pageWidth / 2, y, { align: "center" })
  y += titleLines.length * 7 + 4

  // Organizer
  if (ticket.event.organizer?.organizerName) {
    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(100, 100, 100)
    doc.text(`by ${ticket.event.organizer.organizerName}`, pageWidth / 2, y, { align: "center" })
    y += 8
  }

  // Divider
  doc.setDrawColor(220, 220, 220)
  doc.line(15, y, pageWidth - 15, y)
  y += 8

  // Details section
  const leftX = 18
  doc.setFontSize(9)

  const addField = (label: string, value: string) => {
    doc.setFont("helvetica", "bold")
    doc.setTextColor(100, 100, 100)
    doc.text(label, leftX, y)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(30, 30, 30)
    doc.text(value, leftX + 32, y)
    y += 6
  }

  // Date
  const dateStr = new Date(ticket.event.startDate).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  addField("Date", dateStr)

  // Time
  if (ticket.event.startTime) {
    const timeStr = ticket.event.startTime + (ticket.event.endTime ? ` - ${ticket.event.endTime}` : "")
    addField("Time", timeStr)
  }

  // Location
  const location = ticket.event.eventFormat === "ONLINE"
    ? "Online Event"
    : [ticket.event.venueName, ticket.event.city, ticket.event.country].filter(Boolean).join(", ") || "TBA"
  addField("Location", location)

  // Ticket Type
  addField("Ticket", ticket.ticketType.name)

  // Ticket Number
  addField("Number", `#${ticket.ticketNumber}`)

  // Attendee
  if (ticket.attendeeName) {
    addField("Attendee", ticket.attendeeName)
  }
  if (ticket.attendeeEmail) {
    addField("Email", ticket.attendeeEmail)
  }

  y += 4

  // Divider
  doc.line(15, y, pageWidth - 15, y)
  y += 8

  // QR Code
  if (ticket.qrCode) {
    try {
      const qrSize = 50
      const qrX = (pageWidth - qrSize) / 2
      doc.addImage(ticket.qrCode, "PNG", qrX, y, qrSize, qrSize)
      y += qrSize + 4
      doc.setFontSize(8)
      doc.setTextColor(120, 120, 120)
      doc.text("Show this QR code at the venue for entry", pageWidth / 2, y, { align: "center" })
    } catch {
      doc.setFontSize(10)
      doc.setTextColor(120, 120, 120)
      doc.text("QR code unavailable", pageWidth / 2, y + 20, { align: "center" })
    }
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 8
  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.text("Generated by EventsKona • eventskona.com", pageWidth / 2, footerY, { align: "center" })

  // Download
  doc.save(`ticket-${ticket.ticketNumber}.pdf`)
}
