export const mockEvents = [
  {
    id: "1",
    title: "Summer Music Festival 2025",
    description:
      "Join us for an unforgettable summer music festival featuring top artists from around the world. Three days of incredible performances, food vendors, and entertainment for the whole family.",
    date: "2025-06-15",
    time: "18:00",
    location: "Central Park, New York",
    price: 75,
    category: "music",
    image: "/summer-music-festival-outdoor-stage.jpg",
    attendees: 2450,
    organizer: "EventsKona Productions",
  },
  {
    id: "2",
    title: "Tech Conference 2025",
    description:
      "The premier technology conference bringing together innovators, entrepreneurs, and tech enthusiasts. Learn about the latest trends in AI, blockchain, and web development.",
    date: "2025-07-20",
    time: "09:00",
    location: "San Francisco Convention Center",
    price: 199,
    category: "tech",
    image: "/tech-conference-stage.png",
    attendees: 1850,
    organizer: "Tech Events Inc",
  },
  {
    id: "3",
    title: "Marathon Championship",
    description:
      "Run the scenic 42km marathon through beautiful landscapes. Whether you're a seasoned runner or participating for the first time, this event welcomes all fitness levels.",
    date: "2025-05-10",
    time: "07:00",
    location: "Boston, Massachusetts",
    price: 65,
    category: "sports",
    image: "/marathon-runners-race-track.jpg",
    attendees: 3200,
    organizer: "Boston Sports Events",
  },
  {
    id: "4",
    title: "Contemporary Art Exhibition",
    description:
      "Explore cutting-edge contemporary art from emerging and established artists. This exhibition showcases diverse mediums and perspectives from around the globe.",
    date: "2025-08-01",
    time: "10:00",
    location: "Modern Art Museum, Los Angeles",
    price: 25,
    category: "art",
    image: "/modern-art-gallery.png",
    attendees: 890,
    organizer: "LA Art Collective",
  },
  {
    id: "5",
    title: "Gourmet Food Festival",
    description:
      "Taste culinary creations from top chefs and food vendors. Experience diverse cuisines, cooking demonstrations, and wine pairings in a vibrant festival atmosphere.",
    date: "2025-06-22",
    time: "11:00",
    location: "Riverside Park, Chicago",
    price: 45,
    category: "food",
    image: "/food-festival-outdoor-dining.jpg",
    attendees: 1650,
    organizer: "Chicago Culinary Events",
  },
  {
    id: "6",
    title: "Jazz Night Live",
    description:
      "An intimate evening of live jazz performances featuring world-class musicians. Enjoy smooth melodies, craft cocktails, and an elegant atmosphere.",
    date: "2025-07-05",
    time: "20:00",
    location: "Blue Note Jazz Club, New York",
    price: 85,
    category: "music",
    image: "/jazz-club-live-performance-stage.jpg",
    attendees: 420,
    organizer: "Blue Note Productions",
  },
  {
    id: "7",
    title: "Basketball Tournament",
    description:
      "Competitive basketball tournament featuring amateur and semi-professional teams. Watch exciting matches and support your favorite teams in this thrilling event.",
    date: "2025-05-25",
    time: "14:00",
    location: "Sports Arena, Miami",
    price: 30,
    category: "sports",
    image: "/basketball-game-arena-court.jpg",
    attendees: 2100,
    organizer: "Miami Sports League",
  },
  {
    id: "8",
    title: "Photography Workshop",
    description:
      "Learn professional photography techniques from award-winning photographers. Hands-on workshop covering composition, lighting, and post-processing.",
    date: "2025-06-08",
    time: "09:00",
    location: "Creative Studio, Seattle",
    price: 120,
    category: "art",
    image: "/photography-workshop-camera-equipment.jpg",
    attendees: 65,
    organizer: "Seattle Photography Academy",
  },
]
