export const mockEvents = [
  {
    id: "1",
    title: "Afrobeat Summer Festival 2025",
    description:
      "Join us for an unforgettable summer music festival featuring top Afrobeat artists from across West Africa. Three days of incredible performances, food vendors, and entertainment for the whole family.",
    date: "2025-06-15",
    time: "18:00",
    location: "Eko Atlantic City, Lagos, Nigeria",
    price: 15000,
    currency: "NGN",
    country: "Nigeria",
    category: "music",
    image: "/placeholder.svg?key=2fout",
    attendees: 2450,
    organizer: "EventsKona Productions",
    promoted: true,
  },
  {
    id: "2",
    title: "Tech Conference Accra 2025",
    description:
      "The premier technology conference bringing together innovators, entrepreneurs, and tech enthusiasts from across Africa. Learn about the latest trends in AI, blockchain, and web development.",
    date: "2025-07-20",
    time: "09:00",
    location: "Accra International Conference Centre, Accra, Ghana",
    price: 450,
    currency: "GHS",
    country: "Ghana",
    category: "tech",
    image: "/placeholder.svg?key=6vwpn",
    attendees: 1850,
    organizer: "Tech Events Africa",
    promoted: true,
  },
  {
    id: "3",
    title: "Nairobi Marathon Championship",
    description:
      "Run the scenic 42km marathon through the beautiful landscapes of Nairobi. Whether you're a seasoned runner or participating for the first time, this event welcomes all fitness levels.",
    date: "2025-05-10",
    time: "07:00",
    location: "Uhuru Park, Nairobi, Kenya",
    price: 3500,
    currency: "KES",
    country: "Kenya",
    category: "sports",
    image: "/placeholder.svg?key=ezss6",
    attendees: 3200,
    organizer: "Nairobi Sports Events",
    promoted: false,
  },
  {
    id: "4",
    title: "Contemporary Art Exhibition Lagos",
    description:
      "Explore cutting-edge contemporary art from emerging and established African artists. This exhibition showcases diverse mediums and perspectives from around the continent.",
    date: "2025-08-01",
    time: "10:00",
    location: "Nike Art Gallery, Lagos, Nigeria",
    price: 5000,
    currency: "NGN",
    country: "Nigeria",
    category: "art",
    image: "/placeholder.svg?key=y53r1",
    attendees: 890,
    organizer: "Lagos Art Collective",
    promoted: false,
  },
  {
    id: "5",
    title: "Ghana Food Festival",
    description:
      "Taste culinary creations from top chefs and food vendors across Ghana. Experience diverse cuisines, cooking demonstrations, and traditional Ghanaian dishes in a vibrant festival atmosphere.",
    date: "2025-06-22",
    time: "11:00",
    location: "Independence Square, Accra, Ghana",
    price: 80,
    currency: "GHS",
    country: "Ghana",
    category: "food",
    image: "/placeholder.svg?key=3h1zf",
    attendees: 1650,
    organizer: "Accra Culinary Events",
    promoted: true,
  },
  {
    id: "6",
    title: "Jazz Night Nairobi",
    description:
      "An intimate evening of live jazz performances featuring world-class Kenyan and international musicians. Enjoy smooth melodies, craft cocktails, and an elegant atmosphere.",
    date: "2025-07-05",
    time: "20:00",
    location: "The Alchemist, Nairobi, Kenya",
    price: 4500,
    currency: "KES",
    country: "Kenya",
    category: "music",
    image: "/placeholder.svg?key=nnsjw",
    attendees: 420,
    organizer: "Nairobi Jazz Productions",
    promoted: false,
  },
  {
    id: "7",
    title: "Lagos Basketball Tournament",
    description:
      "Competitive basketball tournament featuring amateur and semi-professional teams from across Nigeria. Watch exciting matches and support your favorite teams in this thrilling event.",
    date: "2025-05-25",
    time: "14:00",
    location: "Teslim Balogun Stadium, Lagos, Nigeria",
    price: 3000,
    currency: "NGN",
    country: "Nigeria",
    category: "sports",
    image: "/placeholder.svg?key=p88ev",
    attendees: 2100,
    organizer: "Lagos Sports League",
    promoted: false,
  },
  {
    id: "8",
    title: "Photography Workshop Accra",
    description:
      "Learn professional photography techniques from award-winning African photographers. Hands-on workshop covering composition, lighting, and post-processing.",
    date: "2025-06-08",
    time: "09:00",
    location: "Nubuke Foundation, Accra, Ghana",
    price: 250,
    currency: "GHS",
    country: "Ghana",
    category: "art",
    image: "/placeholder.svg?key=nk7gy",
    attendees: 65,
    organizer: "Accra Photography Academy",
    promoted: true,
  },
]
